### PR TITLE
Add Makefile and dev env targets

### PR DESCRIPTION
**Pull request by LaikaN57**
This adds a simple `Makefile` which will setup all needed tools on a developers machine to be able to contribute to this repo. They simply just run the commands below (included in new sections in the README.md):
```bash
make venv # run once
source venv/bin/activate # run for every new terminal
```

@mm0 I am moving my PRs here as the source repo seems to be stale. Original: https://github.com/alienbrett/PyAlly/pull/59

### CODE REVIEW

**Comment by mm0** [comment]
Thanks for setting this up @LaikaN57

**Comment by mm0** [comment]
@LaikaN57 I am getting the following error when installing pandas:
```
ERROR: Could not find a version that satisfies the requirement pandas<2.0.0,>=1.2.1
ERROR: No matching distribution found for pandas<2.0.0,>=1.2.1
```
Version 1.1.5 seems to work

**Comment by LaikaN57** [comment]
@mm0 What OS and python version are you running?

Here is my env:
```
(venv) alex@localhost PyAlly % uname -a
Darwin localhost.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
(venv) alex@localhost PyAlly % /usr/local/bin/python3 --version
Python 3.9.2
(venv) alex@localhost PyAlly % venv/bin/python --version
Python 3.9.2
(venv) alex@localhost PyAlly % venv/bin/pip freeze | grep pandas
pandas==1.2.3
```

Anyway, I can change the required min version to `>=1.1.5`. Eventually we should investigate what versions we actually need. I don't thing this project uses anything that is too `pandas` version specific.

**Comment by mm0** [comment]
@LaikaN57 Ubuntu 18.04 and python 3.6.9.  Some other libraries that I use alongside this one require pandas >=0.23.1, so I think it's compatible with older versions of pandas. Any reason for wanting to use a minimum of 1.1.5?

**Comment by LaikaN57** [comment]
I would be interested to see what your `pip freeze` looks like to see what other min panda versions would be acceptable. For now I just changed to the one you listed.

**Comment by mm0** [comment]
> I would be interested to see what your `pip freeze` looks like to see what other min panda versions would be acceptable. For now I just changed to the one you listed.

╰─$ pipdeptree --reverse --packages pandas
pandas==0.23.4
  - mplfinance==0.12.7a5 [requires: pandas]
  - pyEX==0.2.1 [requires: pandas>=0.22]
  - trendln==0.1.10 [requires: pandas>=0.23.1]

**Pull request merged**
